### PR TITLE
Add Oracle table definitions for tag types.

### PR DESCRIPTION
**Pull request by gijskant**

### CODE REVIEW

**Comment by cataphract** [comment]
Indexes should on the `INDX` tablespace.

**Comment by gijskant** [comment]
@cataphract I don't see indexes being created in the `INDX` tablespace in the `i2b2metadata` namespace. If we change it here, then also for the other indexes?

**Comment by cataphract** [comment]
Hmm they should. If you want to fix the rest of the namespace, all the better, otherwise do it just for the new table.

**Comment by gijskant** [comment]
@cataphract Now fixed for the i2b2metadata namespace.

**Comment by cataphract** [comment]
There's something wrong here:

```
ERROR: Failed loading statement  CREATE TABLE "I2B2METADATA"."I2B2_TAG_TYPES"
  ( "TAG_TYPE_ID" NUMBER(18,0) DEFAULT i2b2metadata.i2b2_tag_types_tag_type_id_seq.NEXTVAL NOT NULL ENABLE,
"TAG_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"SOLR_FIELD_NAME" VARCHAR2(255 BYTE),
"NODE_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"VALUE_TYPE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
"SHOWN_IF_EMPTY" CHAR(1 BYTE) NOT NULL ENABLE,
"index" NUMBER,
 CONSTRAINT "I2B2_TAG_TYPES_NODE_TAG_KEY" UNIQUE ("NODE_TYPE", "TAG_TYPE")
 USING INDEX
 TABLESPACE "INDX"  ENABLE,
 CONSTRAINT "I2B2_TAG_TYPES_PKEY" PRIMARY KEY ("TAG_TYPE_ID")
 USING INDEX
 TABLESPACE "INDX"  ENABLE
  ) SEGMENT CREATION DEFERRED
NOCOMPRESS LOGGING
TABLESPACE "TRANSMART"  from i2b2metadata/i2b2_tag_types.sql
ERROR: Error loading file i2b2metadata/i2b2_tag_types.sql: java.sql.SQLSyntaxErrorException: ORA-02289: sequence does not exist
```

I've now configured travis correctly to test oracle.

**Comment by cataphract** [comment]
I'm looking into it.

**Comment by cataphract** [comment]
The problem is that oracle doesn't detect the dependency of the table on the sequence (as shown by `DBA_DEPENDENCIES`). The default has to be changed to a trigger.

**Pull request merged**
